### ISSUE TITLE
const result = city64("cs");

### ISSUE THREAD

**Issue by xietao1233** [BoogeeDoo/node-cityhash#1]
Assertion failed: native function `new_uint64` called before runtime initialization
/mnt/data/src/node/test/node_modules/bling-hashes-js/dist/export.js:121
      throw ex;
      ^

Error: abort(Assertion failed: native function `new_uint64` called before runtime initialization) at Error: 
    at jsStackTrace (/mnt/data/src/node/test/node_modules/bling-hashes-js/dist/export.js:12188:19)
    at stackTrace (/mnt/data/src/node/test/node_modules/bling-hashes-js/dist/export.js:12205:16)
    at abort (/mnt/data/src/node/test/node_modules/bling-hashes-js/dist/export.js:11894:44)
    at assert (/mnt/data/src/node/test/node_modules/bling-hashes-js/dist/export.js:11081:5)
    at /mnt/data/src/node/test/node_modules/bling-hashes-js/dist/export.js:11966:5
    at ccall (/mnt/data/src/node/test/node_modules/bling-hashes-js/dist/export.js:11138:18)
    at Object.newUInt64 (/mnt/data/src/node/test/node_modules/bling-hashes-js/dist/export.js:11150:12)
    at Object.exports.city64 (/mnt/data/src/node/test/node_modules/bling-hashes-js/lib/bling.js:70:19)
    at Object.<anonymous> (/mnt/data/src/node/test/src/main.ts:70:16)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at abort (/mnt/data/src/node/test/node_modules/bling-hashes-js/dist/export.js:11900:11)
    at assert (/mnt/data/src/node/test/node_modules/bling-hashes-js/dist/export.js:11081:5)
    at /mnt/data/src/node/test/node_modules/bling-hashes-js/dist/export.js:11966:5
    at ccall (/mnt/data/src/node/test/node_modules/bling-hashes-js/dist/export.js:11138:18)
    at Object.newUInt64 (/mnt/data/src/node/test/node_modules/bling-hashes-js/dist/export.js:11150:12)
    at Object.exports.city64 (/mnt/data/src/node/test/node_modules/bling-hashes-js/lib/bling.js:70:19)
    at Object.<anonymous> (/mnt/data/src/node/test/src/main.ts:70:16)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Module.m._compile (/mnt/data/home/xxxxxx/.nvm/versions/node/v12.16.3/lib/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1153:10)

**Comment by chaoyangnz** [comment]
same issue. never worked
